### PR TITLE
styled the h1/title "Race Registration" in the form

### PR DESCRIPTION
**Pull request by Andy-Not**
let me know if I should make any changes

### CODE REVIEW

**Comment by dodavid808** [comment]
@Andy-Not could i get a screen capture of what it looks like? i could run it. but just getting you used to commenting on here.

**Comment by Andy-Not** [comment]
> @Andy-Not could i get a screen capture of what it looks like? i could run it. but just getting you used to commenting on here.

image

**Comment by vesutiiji** [comment]
it looks like a button. keep the shadow, change the blue to white, change font color from white to black, then good.

**Comment by dodavid808** [comment]
> it looks like a button. keep the shadow, change the blue to white, change font color from white to black, then good.

i know its style and its a personal taste. but for now, do what jack says so you can get the hang of Pull Request (PR) fixes.

**Pull request closed without merging**
